In [1]:
import numpy as np

In [2]:
L = [1,2,3]

In [3]:
A = np.array(L)

In [5]:
L.append(4)

In [6]:
L

[1, 2, 3, 4]

In [7]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [8]:
L + [5]

[1, 2, 3, 4, 5]

In [9]:
A

array([1, 2, 3])

In [10]:
A + np.array([4])

array([5, 6, 7])

In [11]:
A

array([1, 2, 3])

In [12]:
A + np.array([4,5,6])

array([5, 7, 9])

In [13]:
2 * A

array([2, 4, 6])

In [14]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [15]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [16]:
L2 = []
for e in L:
    L2.append(e + 3)
L2

[4, 5, 6, 7]

In [17]:
L2 ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [18]:
L2 = [ e ** 2 for e in L]
L2

[1, 4, 9, 16]

In [19]:
A

array([1, 2, 3])

In [20]:
A**2

array([1, 4, 9])

In [21]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])