In [1]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import sympy as sp

In [2]:
a = np.array([1, 2])
b = np.array([3, 4])

In [3]:
a
b

array([1, 2])

array([3, 4])

In [6]:
a * b  # element wise
np.sum(a * b)
(a * b).sum()

array([3, 8])

11

11

In [8]:
a.dot(b)
np.dot(a, b)
a @ b

11

11

11

In [10]:
np.linalg.norm(a) # vector magnitude

2.23606797749979