In [1]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import sympy as sp

In [2]:
L = [
    [1, 2],
    [3, 4],
]
L

[[1, 2], [3, 4]]

In [3]:
L[0][1]

2

In [4]:
A = np.array(L)
A

array([[1, 2],
       [3, 4]])

In [7]:
A[0][1]
A[0, 1]

2

2

In [8]:
A[:, 1]  # get all row of  "column 1"

array([2, 4])

In [9]:
A[:, 0]

array([1, 3])

In [10]:
A
A.T

array([[1, 2],
       [3, 4]])

array([[1, 3],
       [2, 4]])

In [11]:
np.exp(A)
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [17]:
B = np.array([
    [1,2,3],
    [4,5,6],
])
B

B.shape

A
A.shape

array([[1, 2, 3],
       [4, 5, 6]])

(2, 3)

array([[1, 2],
       [3, 4]])

(2, 2)

In [18]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [20]:
A.dot(B.T)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [23]:
A
np.linalg.det(A)
np.linalg.inv(A)
np.linalg.inv(A).dot(A)

array([[1, 2],
       [3, 4]])

-2.0000000000000004

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [27]:
A
A.trace()
np.trace(A)
np.diag(A)

array([[1, 2],
       [3, 4]])

5

5

array([1, 4])

In [28]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [29]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [31]:
Lam, V = np.linalg.eig(A)
Lam
V

array([-0.37228132,  5.37228132])

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [34]:
V[:,0] * Lam[0]

array([ 0.30697009, -0.21062466])

In [35]:
A @ V[:, 0]

array([ 0.30697009, -0.21062466])

In [37]:
V[:,0] * Lam[0] == A @ V[:, 0]

array([ True, False])

In [38]:
np.allclose(V[:,0] * Lam[0], A @ V[:, 0])

True