In [1]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import sympy as sp

In [2]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.eye(3) # I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.random.random((2, 3)) # uniform 0 1 dist

array([[0.84140485, 0.68665433, 0.40587339],
       [0.99461257, 0.24817436, 0.23286774]])

In [7]:
np.random.randn(2, 3) # gaussian dist

array([[ 1.06920993, -3.01345919, -0.94933906],
       [ 0.44835911,  1.08595952, -0.58162318]])

In [8]:
R = np.random.randn(10000)

In [12]:
R.mean()
R.var()
R.std()

-0.008243070823686917

0.9812978528574259

0.990604791456929

In [13]:
R = np.random.randn(10000, 3)

In [15]:
R.mean(axis=0)

array([ 0.02419585, -0.00429002,  0.01078963])

In [17]:
R.mean(axis=1)
R.mean(axis=1).shape

array([-0.52746242, -0.61167345,  1.01429482, ..., -0.08015559,
       -0.11330821,  0.19042984])

(10000,)

In [19]:
np.cov(R).shape

(10000, 10000)

In [21]:
np.cov(R.T)
np.cov(R, rowvar=False)

array([[ 1.03427397, -0.02665389,  0.00821065],
       [-0.02665389,  1.00484528, -0.00399803],
       [ 0.00821065, -0.00399803,  1.01211909]])

array([[ 1.03427397, -0.02665389,  0.00821065],
       [-0.02665389,  1.00484528, -0.00399803],
       [ 0.00821065, -0.00399803,  1.01211909]])

In [22]:
np.random.randint(0, 10, size=(3,3))

array([[8, 0, 4],
       [5, 3, 0],
       [0, 9, 1]])

In [24]:
np.random.choice(10, size=(3,3))

array([[8, 5, 9],
       [6, 8, 7],
       [0, 5, 5]])