In [1]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import sympy as sp

In [2]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
A = np.ones((2,2,3))

A

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [4]:
a = [
    [[1,1], [1,1]], 
    [[1,1], [1,1]], 
    [[1,1], [1,1]],
]

A = np.array(a)

A

A.shape

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

(3, 2, 2)

In [5]:
A = np.ones((2,2,3,4))

A

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [6]:
arr = np.arange(24).reshape(2,3,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# axis = 0

In [10]:
arr[0]
arr[1]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
arr[0] + arr[1]

np.sum(arr, axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [17]:
arr

arr[0]

arr[0][0]

arr[0, 0, :]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([0, 1, 2, 3])

array([0, 1, 2, 3])

In [28]:
# keep the first axis fixed, and sum along the second axis=1
# we have 6 elements 3 along each from the first axis 0

arr[0, 0, :]
arr[0, 1, :]
arr[0, 2, :]

print()

arr[1, 0, :]
arr[1, 1, :]
arr[1, 2, :]

print()

arr

np.sum(arr, axis=1)

array([0, 1, 2, 3])

array([4, 5, 6, 7])

array([ 8,  9, 10, 11])

array([12, 13, 14, 15])

array([16, 17, 18, 19])

array([20, 21, 22, 23])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [27]:
arr[0, 0, 0]
arr[0, 0, 1]
arr[0, 0, 2]
arr[0, 0, 3]

arr

np.sum(arr, axis=2)

0

1

2

3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array([[ 6, 22, 38],
       [54, 70, 86]])

In [31]:
a = np.array([1,2,3])
a
a.ndim
a.shape
a.dtype

array([1, 2, 3])

1

(3,)

dtype('int64')

In [35]:
b = np.array(5)
c = np.array(3.8)
b
b.ndim
c
c.ndim

array(5)

0

array(3.8)

0

In [44]:
a = [[1,2,3],[5,6,7], [8,9,10]]
A = np.array(a)
A
A.shape
A.sum(axis=0)
A.sum(axis=1)

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

(3, 3)

array([14, 17, 20])

array([ 6, 18, 27])

In [45]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [47]:
b = [
    [[1,2], 
     [3,4]],
    
    [[5,6], 
     [7,8]],
    
    [[9,10], 
     [11,12]],
]
B = np.array(b)
B

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [48]:
B.shape

(3, 2, 2)

In [52]:
a = np.array([[40,10,30],[10,5,15]])
a

a.sort(axis=0)
a

a.sort(axis=1)
a

array([[40, 10, 30],
       [10,  5, 15]])

array([[10,  5, 15],
       [40, 10, 30]])

array([[ 5, 10, 15],
       [10, 30, 40]])

In [55]:
a = np.array([1,2,3], dtype=np.int8)
a

array([1, 2, 3], dtype=int8)

In [56]:
array_2d = np.array(
(np.arange(0,8,2), np.arange(1,8,2))
)

array_2d

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [62]:
array_2d = array_2d.reshape((2, 1, 4))

array_2d

array([[[0, 2, 4, 6]],

       [[1, 3, 5, 7]]])

In [61]:
array_2d.reshape((8))

array([0, 2, 4, 6, 1, 3, 5, 7])

In [64]:
np.zeros((2,2), dtype=np.int8)

array([[0, 0],
       [0, 0]], dtype=int8)

In [65]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [71]:
emp = np.empty((3, 3))

In [72]:
emp

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.5e-323, 3.0e-323, 3.5e-323],
       [4.0e-323, 4.4e-323, 4.9e-323]])

In [75]:
eye_arr = np.eye(5, k=6)

In [76]:
eye_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [95]:
a = np.zeros((3,3), dtype=np.int64)
a.fill(8)

In [96]:
a += 3
a /= 3
a

UFuncTypeError: Cannot cast ufunc 'divide' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [97]:
a = np.zeros((3,3), dtype=np.int64)
a.fill(2)

In [98]:
a

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [99]:
arr_sum = np.sum(a)
arr_sum

18

In [100]:
b = np.arange(1,10).reshape((3,3))
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
b.sum(axis=0)
b.sum(axis=1)

array([12, 15, 18])

array([ 6, 15, 24])

In [104]:
b.prod(axis=0)

array([ 28,  80, 162])

In [105]:
b.mean()

5.0

In [106]:
b
b.max()
b.argmax()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

9

8

In [107]:
b.ptp() # b.max() - b.min()

8

# flatten arrays

In [117]:
b
b.reshape(b.size)
b.flatten() # makes a copy
b.ravel() # makes a view
print()

c = b.ravel()
c
c += 100
c

b

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

array([101, 102, 103, 104, 105, 106, 107, 108, 109])

array([101, 102, 103, 104, 105, 106, 107, 108, 109])

array([101, 102, 103, 104, 105, 106, 107, 108, 109])

array([101, 102, 103, 104, 105, 106, 107, 108, 109])

array([201, 202, 203, 204, 205, 206, 207, 208, 209])

array([[201, 202, 203],
       [204, 205, 206],
       [207, 208, 209]])

In [118]:
arr_repeat = np.repeat(255, 3)
arr_repeat

array([255, 255, 255])

In [120]:
b = np.arange(1,10).reshape((3,3))
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [124]:
b
arr_repeat = np.repeat(b, 3, axis=0)
arr_repeat

arr_repeat = np.repeat(b, 3, axis=1)
arr_repeat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9],
       [7, 8, 9]])

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [4, 4, 4, 5, 5, 5, 6, 6, 6],
       [7, 7, 7, 8, 8, 8, 9, 9, 9]])

In [126]:
arr_uni = np.unique(arr_repeat, axis=1)
arr_uni

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [130]:
np.diagonal(b, offset=1)

array([2, 6])

In [132]:
np.swapaxes(b, 0, 1)
b.transpose(1, 0)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [133]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [137]:
np.floor(b / 2)

array([[0., 1., 1.],
       [2., 2., 3.],
       [3., 4., 4.]])

In [135]:
b // 2

array([[0, 1, 1],
       [2, 2, 3],
       [3, 4, 4]])

In [139]:
a = np.repeat(2, 9).reshape((3,3))
a

b = np.arange(1, 10).reshape((3,3))
b

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [140]:
np.matmul(a, b)

array([[24, 30, 36],
       [24, 30, 36],
       [24, 30, 36]])

In [141]:
a.dot(b)

array([[24, 30, 36],
       [24, 30, 36],
       [24, 30, 36]])