In [1]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import sympy as sp

In [3]:
a = np.arange(1, 5)
b = np.array([6,8,3,2])

In [6]:
a
b

array([1, 2, 3, 4])

array([6, 8, 3, 2])

In [7]:
a + b

array([ 7, 10,  6,  6])

In [8]:
a -b

array([-5, -6,  0,  2])

In [9]:
a * b

array([ 6, 16,  9,  8])

In [10]:
a / b

array([0.16666667, 0.25      , 1.        , 2.        ])

In [12]:
np.around(a/b, 2)

array([0.17, 0.25, 1.  , 2.  ])

In [15]:
a
b

expo = a ** b
expo

array([1, 2, 3, 4])

array([6, 8, 3, 2])

array([  1, 256,  27,  16])