In [1]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import sympy as sp

In [20]:
ls = [4,8,15,16,23,42]
array = np.array(ls)
array.dtype

dtype('int64')

In [21]:
array = np.array(ls, dtype=np.int32)
array

array([ 4,  8, 15, 16, 23, 42], dtype=int32)

In [22]:
array.size

6

In [23]:
array.nbytes

24

# Slicing

In [24]:
array = np.array(ls)

In [35]:
array
array[3:]

array([ 4,  8, 15, 16, 23, 42])

array([16, 23, 42])

In [36]:
array[:3+1]

array([ 4,  8, 15, 16])

In [37]:
array[:82]

array([ 4,  8, 15, 16, 23, 42])