In [1]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import sympy as sp

# Sorting

In [11]:
ls = [4,8,15,16,42,23]

In [13]:
array = np.array(ls)
array

array([ 4,  8, 15, 16, 42, 23])

In [15]:
np.sort(array)

array([ 4,  8, 15, 16, 23, 42])

# Copies vs Views

In [29]:
# Reverse an array
array = np.array([4,8,15,16,23,42])
reverse_array = array[::-1]
reverse_array

reverse_array[0] = 1000
reverse_array
array

# Slicing created a view

array([42, 23, 16, 15,  8,  4])

array([1000,   23,   16,   15,    8,    4])

array([   4,    8,   15,   16,   23, 1000])

In [31]:
array = np.array([-4, 8, 15, 16, 23, 42])
positive_array = np.abs(array) # create a copy

positive_array
array

positive_array[0] = 1000
positive_array
array

array([ 4,  8, 15, 16, 23, 42])

array([-4,  8, 15, 16, 23, 42])

array([1000,    8,   15,   16,   23,   42])

array([-4,  8, 15, 16, 23, 42])

# Aggregate Functions

In [ ]:
array = np.array([4,8,15,16,23,42])
