In [1]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

In [2]:
my_ls = [
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
]

In [4]:
matrix = np.array(my_ls)

matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
vector = np.arange(5)
vector

array([0, 1, 2, 3, 4])

In [6]:
list(vector)

[0, 1, 2, 3, 4]

In [7]:
list(matrix)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [8]:
matrix.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [9]:
matrix[0] = [3,3,3]

In [10]:
matrix

array([[ 3,  3,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
matrix[2][1]
matrix[2,1]

8

8

In [12]:
matrix[2,1] = 100

In [13]:
matrix

array([[  3,   3,   3],
       [  4,   5,   6],
       [  7, 100,   9],
       [ 10,  11,  12]])

In [14]:
matrix[:, 2]

array([ 3,  6,  9, 12])

# Atrributes

In [17]:
vector = np.arange(5)

In [18]:
vector.ndim

1

In [20]:
matrix = np.array([[1,2], [2,4], [1,5]])

In [21]:
matrix.ndim

2

In [22]:
vector.size

5

In [23]:
matrix.dtype

dtype('int64')

In [24]:
matrix.shape

(3, 2)

In [25]:
matrix

array([[1, 2],
       [2, 4],
       [1, 5]])

In [26]:
matrix.shape[0] = 1

TypeError: 'tuple' object does not support item assignment

In [27]:
t = (0,1)
t[0] = 1

TypeError: 'tuple' object does not support item assignment

In [28]:
vector

array([0, 1, 2, 3, 4])

In [30]:
row_vector = vector[np.newaxis, :]
row_vector

array([[0, 1, 2, 3, 4]])

In [31]:
row_vector.shape

(1, 5)

In [32]:
vector

array([0, 1, 2, 3, 4])

In [33]:
col_vector = vector[:, np.newaxis]
col_vector

array([[0],
       [1],
       [2],
       [3],
       [4]])