In [1]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

In [15]:
arr = np.arange(1, 25).reshape((2,3,4))
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [27]:
arr.reshape((2, -1))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [19]:
A = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

In [20]:
A.reshape(-1, 4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
np.concatenate(A, axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [8]:
np.reshape(A, (2, -1), order='C')

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
np.concatenate(A, axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [13]:
A

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])