In [1]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

In [2]:
# Create a 1D vector
vec = np.array([1, 2, 3])

# Number of times to repeat the vector as a column
n = 4

# Create a matrix by repeating the vector as a column
matrix = np.tile(vec[:, np.newaxis], (1, n))
print(matrix)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


In [3]:
vec[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [21]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [16]:
np.tile(a[np.newaxis, :, :], (2, 1, 1))

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [18]:
np.repeat(a[np.newaxis, :, :], 2, axis=0).shape

(2, 2, 2)

In [22]:
np.tile(a, (2, 1, 1))

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [36]:
vec = np.array([1, 2, 3])
vec

array([1, 2, 3])

In [32]:
vec = np.arange(1, 19)
vec

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [44]:
np.tile(vec, (1,2))

array([[1, 2, 3, 1, 2, 3]])

In [41]:
vec.reshape(3, -1)

array([[1],
       [2],
       [3]])

In [42]:
vec[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [43]:
vec[np.newaxis, :]

array([[1, 2, 3]])

In [53]:
arr = np.arange(1,5).reshape((2,2))

In [54]:
arr

array([[1, 2],
       [3, 4]])

In [52]:
np.tile(arr[np.newaxis, :, :], (2, 1, 1))

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [56]:
arr = np.arange(1,5).reshape((2,2))
np.tile(arr, (2, 1, 1))

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [58]:
arr = np.arange(1,5).reshape((2,2))
np.repeat(arr, 2, axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [59]:
arr = np.arange(1,5).reshape((2,2))
np.repeat(arr[np.newaxis, :, :], 2, axis=0)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [64]:
arr = np.arange(1,4)
mean_2d = np.repeat(arr[:, np.newaxis], 3, axis=1)

In [65]:
mean_3d = np.repeat(mean_2d[np.newaxis,:,:], 2, axis=0)

mean_3d

array([[[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]],

       [[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]])