In [2]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

In [31]:
w=np.array([[1,2,3],[4,5,6],[7,8,9]])
x=np.array([7,2,3])

In [32]:
w
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([7, 2, 3])

In [33]:
w.shape
x.shape

(3, 3)

(3,)

In [36]:
w.dot(x)
x.dot(w)

array([20, 56, 92])

array([36, 48, 60])

In [35]:
x.dot(w) == np.dot(x, w)

array([ True,  True,  True])

In [24]:
x.dot(w) == w@x

array([False, False, False])

In [10]:
w@x

array([20, 56, 92])

In [11]:
x@w

array([36, 48, 60])

# change x shape

In [26]:
x=x.reshape(-1, 1)

In [27]:
x.shape

(3, 1)

In [28]:
x

array([[7],
       [2],
       [3]])

In [29]:
w

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
x.dot(w)

ValueError: shapes (3,1) and (3,3) not aligned: 1 (dim 1) != 3 (dim 0)